import LegalPage from '@/components/legal/LegalPage'

export default function TermsOfServicePage() {
  return (
    <LegalPage
      kicker="Terms"
      title={<>Terms of <span className="gradient-text">Service.</span></>}
      lastUpdated="22 April 2026"
    >
      <p>
        These terms govern your use of voidexa.com and any connected apps,
        products, or services operated by voidexa (&ldquo;we&rdquo;, &ldquo;us&rdquo;).
        By creating an account, purchasing GHAI credits, or otherwise using the
        service, you agree to these terms. If you do not agree, do not use the
        service.
      </p>

      <h2>1. Operator</h2>
      <p>
        voidexa is operated by <strong>Jimmi Wulff</strong>, registered in
        Denmark under <strong>CVR 46343387</strong>, with principal place of
        business in Vordingborg, Denmark. voidexa.com is not affiliated with
        voidexa.online or any similarly named third party.
      </p>

      <h2>2. Accounts</h2>
      <p>
        You must be at least 13 years old to create an account. You are
        responsible for keeping your credentials secure and for all activity on
        your account. We may suspend or close accounts that violate these terms,
        are used for fraud or abuse, or are inactive for more than 24 months
        with a zero GHAI balance.
      </p>

      <h2>3. GHAI credits</h2>
      <p>
        GHAI is a <strong>non-refundable, non-transferable digital platform
        credit</strong>. One euro buys 100 GHAI at list price. GHAI is:
      </p>
      <ul>
        <li><strong>Not a cryptocurrency.</strong> GHAI has no blockchain, no mining, no staking, and no secondary market.</li>
        <li><strong>Not an investment.</strong> GHAI does not carry any expectation of profit, return, or dividend. We make no yield, earning, or appreciation claims.</li>
        <li><strong>Not a security.</strong> GHAI confers no ownership or governance rights in voidexa, its assets, or its revenue.</li>
        <li><strong>Not legal tender.</strong> GHAI can only be used to purchase digital goods and services inside the voidexa platform.</li>
        <li><strong>Not cash-redeemable.</strong> GHAI cannot be converted back to fiat currency.</li>
      </ul>
      <p>
        Purchases of GHAI are final. We may issue refunds at our sole discretion
        if we determine a purchase was made in error or affected by a technical
        fault on our side. GHAI balances may be forfeited if the account is
        closed for breach of these terms.
      </p>
      <p>
        GHAI pricing, cosmetic catalog prices, and feature pricing may change.
        Changes do not affect GHAI you already own.
      </p>

      <h2>4. User-generated content</h2>
      <p>
        Some parts of the service (Break Room, Universe Wall, Trading Hub
        strategy descriptions, deck names, profile bios, ship tags) let you post
        content. You keep ownership of what you post. You grant voidexa a
        non-exclusive, worldwide, royalty-free licence to host, display,
        transmit, and display derivatives of that content for the purpose of
        operating the service.
      </p>
      <p>You agree not to post content that:</p>
      <ul>
        <li>Is unlawful, defamatory, harassing, or hateful</li>
        <li>Infringes copyright, trademark, or other intellectual property</li>
        <li>Contains malware or links to phishing or scam content</li>
        <li>Promotes financial products, tokens, or investment schemes without our written approval</li>
        <li>Contains personal data about third parties without their consent</li>
      </ul>
      <p>
        We may remove content and suspend accounts that break these rules.
        Trading strategies shared in the Trading Hub are informational only and
        are not financial advice.
      </p>

      <h2>5. AI features</h2>
      <p>
        Void Chat, the Quantum debate engine, the AI trading bot, and other AI
        features produce output generated by third-party large language models
        and machine-learning systems. Output:
      </p>
      <ul>
        <li>Can be wrong, incomplete, or out of date. Verify anything important before acting on it.</li>
        <li>Is not financial, legal, medical, or professional advice.</li>
        <li>Is provided on an &ldquo;as is&rdquo; basis with no warranty as to accuracy or fitness.</li>
      </ul>
      <p>
        Backtested and historical trading results shown on voidexa.com are
        historical only and are not a promise of future performance. You are
        solely responsible for any trading or financial decisions.
      </p>

      <h2>6. Physical products</h2>
      <p>
        When voidexa sells physical products (for example hardware such as the
        AEGIS security monitor), Danish consumer protection law applies,
        including the <strong>2-year reklamationsret</strong> under
        K&oslash;beloven for defects that were present at the time of delivery,
        and the <strong>14-day return right</strong> under the Danish{' '}
        <em>Forbrugeraftaleloven</em> for distance sales to consumers. The
        return right does not apply to digital goods (including GHAI) that have
        been delivered and activated with your consent.
      </p>

      <h2>7. Acceptable use</h2>
      <ul>
        <li>Do not reverse engineer, scrape at scale, or resell the service without written permission.</li>
        <li>Do not use the service to build a directly competing AI trading or compression product.</li>
        <li>Do not attempt to access accounts, data, or systems you are not authorised to use.</li>
        <li>Respect API rate limits and fair-use quotas.</li>
      </ul>

      <h2>8. Service changes and availability</h2>
      <p>
        voidexa.com is an evolving platform. We may add, change, or remove
        features at any time. We aim for high availability but do not guarantee
        uninterrupted service. Scheduled maintenance is announced in-app when
        practical.
      </p>

      <h2>9. Liability</h2>
      <p>
        To the maximum extent allowed by Danish law, voidexa&rsquo;s total
        liability arising out of or in connection with the service is limited
        to the amount you paid voidexa in the 12 months preceding the event
        giving rise to the claim. voidexa is not liable for indirect, incidental,
        or consequential damages, including lost profits, lost data, or lost
        trading opportunities. Nothing in these terms limits any liability that
        cannot be limited under Danish mandatory consumer law.
      </p>

      <h2>10. Termination</h2>
      <p>
        You can close your account at any time from your profile or by emailing{' '}
        <a href="mailto:contact@voidexa.com">contact@voidexa.com</a>. We can
        suspend or terminate your access if you materially breach these terms,
        with reasonable notice where possible. Unused GHAI is forfeited on
        termination for breach.
      </p>

      <h2>11. Governing law and jurisdiction</h2>
      <p>
        These terms are governed by Danish law. Disputes that cannot be
        resolved out of court are submitted to the exclusive jurisdiction of
        the Danish courts, with <strong>Vordingborg retskreds</strong> as
        first-instance venue. Consumers retain any right they have under their
        country of residence to bring a claim locally under Regulation (EU)
        1215/2012.
      </p>

      <h2>12. Changes to these terms</h2>
      <p>
        We may update these terms. Material changes are announced by email or
        in-app notice 14 days before taking effect. Continued use after the
        effective date is acceptance of the new terms.
      </p>

      <h2>13. Disclaimer</h2>
      <p>
        This document is a plain-language baseline, sufficient for technical
        compliance. It is not a substitute for independent legal advice. A full
        solicitor review is tracked internally as AFS-37.
      </p>
    </LegalPage>
  )
}
